### ISSUE TITLE
Question: Can you elaborate on the compiled versus interpreted dichotomy?

### ISSUE THREAD

**Issue by cognociente** [fsprojects/FSharp.Quotations.Evaluator#12]
I have just started looking into Quotation Expressions and your project looks to add value in that sphere. Thanks.

I have looked through the tutorial in the repo and I see that you mention that both 
 - QuotationEvaluator.Evaluate
 - QuotationEvaluator.Compile
are actually compiled.

When you say "compiled" do you mean that you have forced the runtime to compile the expression into MSIL and then machine code at the point of invocation? I would then assume that a first invocation would take some sort of a performance hit and subsequent invocations would have zero overhead? Is that the case?

Lastly (and less important), why would you want an interpreted version for "Evaluate" if you have the compiled one?

Kind Regards
Sam

PS: I don't have a background in LINQ. Coming to F# without much C# baggage.

**Comment by dsyme** [comment]
Hi @cognociente 

Yes, there's a one-time performance hit on compilation/evaluation.  An interpreted version would avoid this but be slower.

Cheers
don

**Comment by manofstick** [comment]
Hi @cognociente 

I'm assuming you were happy with Don's answer, and so I'm closing this issue.

Regards,
Oaul.
