### ISSUE TITLE
Unobsolete Compile : Expr<'T> -> 'T 

### ISSUE THREAD

**Issue by kkm000** [fsprojects/FSharp.Quotations.Evaluator#13]
I am using `Compile` to get what the method says: a compiled version of the expression. This compiled function will be called later quite often (I am parsing a DSL, and the function becomes part of the compiled AST, later evaluated as part of an expression).

If I would do as the warning says and `Evaluate` the expression on every call, I think I would take a 2 order of magnitude performance hit. This is an argument for not marking it obsolete currently.

Also, I do not believe that it will make sense to try to get rid of Compile vs Evaluate option even in the future, when Evaluate interprets the expression. Possible performance hit would be too great in some applications--unless the interpreting Evaluate is as efficient as compiled function call. This is an argument for not marking it obsolete in the future.

**Comment by manofstick** [comment]
Evaluate doesn't, and never has (whilst I have maintained the code) done anything other than the same thing Compile does.

So there should be no orders of magnitude speed difference; and if you are getting that I'm surprised and submit a issue with a code example (I'm writing this from memory, not looking at the code, but I'm pretty sure I remember correctly! You can see the discussion under #9)
