### ISSUE TITLE
Update to FSharp.Core 4.1

### ISSUE THREAD

**Issue by aaronpalmer** [fsprojects/FSharp.Quotations.Evaluator#18]
Issues with Expr serialization in Akka.net.  Traced it to a version conflict with FSharp.Quotations.Evaluator using an old version of FSharp.Core.

**Comment by dsyme** [comment]
@aaronpalmer Shouldn't you just be using the later FSharp.Core at runtime?  Does the library really need to be recompiled?

**Comment by aaronpalmer** [comment]
@dsyme There must be more to the serialization issue than I initially suspected.  I had added binding redirects to 4.4.1.0, and still get an issue with serialization of the Expr being sent remote within an Akka.net cluster.  The expression is valid on the sending side, but at the destination it is "null" (Throws a null reference exception when I call QuotationEvaluator.EvaluateUntyped command.Code  (where Code: Expr) .  Perhaps it's an issue with Akka.net.  I'll close this and do more research.  Thank you.

**Comment by dsyme** [comment]
@aaronpalmer OK, thanks for the update!
