### ISSUE TITLE
Possible FSharp.Quotations.Evaluator.Hacks nuget packaging problem

### ISSUE THREAD

**Issue by kennethito** [fsprojects/FSharp.Quotations.Evaluator#23]
### Description

Unexpected runtime exception being thrown when using this library via nuget.

Message: System.IO.FileNotFoundException : Could not load file or assembly 'FSharp.Quotations.Evaluator.Hacks, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Pretty sure this is just a packaging spec problem.  I see the Hacks dll in the nupkg lib folder but its not being referenced by my project on adding the nuget package.

### Repro steps

Execute 

[Akka.FSharp.Tests.ApiTests.``can serialize expression decider``](https://github.com/kennethito/akka.net/blob/feature/resurrect-akka-fsharp/src/core/Akka.FSharp.Tests/ApiTests.fs#L25)

in 

https://github.com/kennethito/akka.net/tree/feature/resurrect-akka-fsharp

### Related information 

* Windows 10 16299
* Executing via a netcoreapp2.0 unit test project, the code under test is netstandard2.0
* FSharp.Quotations.Evaluator 1.1.0
* FSharp.Core 4.3.4

**Comment by manofstick** [comment]
@eiriktsarpalis - Are you happy to look at this?

**Comment by eiriktsarpalis** [comment]
I think I know what's wrong. Will try to fix over the weekend.

**Comment by kennethito** [comment]
Awesome, sounds great!
