### ISSUE TITLE
Cannot evaluate sprintf/printf with more than two parameters

### ISSUE THREAD

**Issue by akbcode** [fsprojects/FSharp.Quotations.Evaluator#26]
### Description

I am unable to evaluate sprintf when it is given more than two parameters.
This works

    <@ sprintf "An int %d" 10 @>

This does not work though

    <@ sprintf "An int %d, a double %f" 10 50.50 @>

### Repro steps

    let t = <@ sprintf "An int %d, a double %f" 10 50.50 @>
    t.EvaluateUntyped();;

### Expected behavior

Quotation is evaluated

### Actual behavior

System.ArgumentException is thrown

    Expression of type 
    'FSharp.Quotations.Evaluator.Tools+FuncFSharp`3[Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Double,System.String]],System.Int32,FSharp.Quotations.Evaluator.Tools+FuncFSharp`3[Microsoft.FSharp.Core.FSharpFunc`2[System.Double,System.String],System.Double,System.String]]'
    cannot be used for parameter of type 
    'Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Double,System.String]]'
    of method 'System.String InvokeFast[String]
    (Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,Microsoft.FSharp.Core.FSharpFunc`2[System.Double,System.String]], Int32, Double)'
    Parameter name: arg0

### Known workarounds

Use string concatenation

### Related information 

* Operating system - macOS 10.13.6
* Branch - master
* .NET Runtime, CoreCLR or Mono Version - Mono 5.16.0.173
* Performance information, links to performance testing scripts

**Comment by manofstick** [comment]
@akbcode

Thanks for analysis. I've got a long weekend this week, so I'll try to find some time to get to the bottom of this.

**Comment by manofstick** [comment]
@akbcode 

I had a quick look, and if you just want to build yourself a temporary fix then you can modify [some code here](https://github.com/fsprojects/FSharp.Quotations.Evaluator/blob/master/src/FSharp.Quotations.Evaluator/QuotationsEvaluator.fs#L441-L454):

            if true || argsCount > 19 then
                // due to limitations of compiling linq quotations we have this fallback where we just pop
                // off a single argument and try again. This gives very poor runtime performance, but I'm
                // guessing (hoping?) that there aren't too many real world functions that have > 19 arguments.
                let v, body = firstVar, firstBody

                let vP = ConvVar v
                let env = { env with varEnv = Map.add v (vP |> asExpression) env.varEnv }
                let tyargs = [| v.Type; body.Type |]
                let bodyP = ConvExpr env body
                let convType = typedefof<System.Func<obj,obj>>.MakeGenericType tyargs
                let convDelegate = Expression.Lambda(convType, bodyP, [| vP |]) |> asExpression
                Expression.Call(typeof<FuncConvert>,"ToFSharpFunc",tyargs,[| convDelegate |]) |> asExpr
            else

Note there are two changes - the first is making the `if` unconditional, the second is changing `System.Converter<obj,obj>` to `System.Func<obj,obj>` (really this branch should have been tested and this would have broken when the `FuncConvert` API changed, but that's another issue...)

Anyway, this change will make your code work (i.e. fix this issue), but I don't really want to run with this as the final fix as it slow down use of lambdas _a lot_! (the performance tests run 10x slower). So, as said before I'll put some proper time into it over my coming long weekend... (hopefully, but my children might have something to say about that...)

**Comment by akbcode** [comment]
@manofstick 
Thanks for looking into it. This solves my problem for now but I don't mind waiting for a proper fix.

**Comment by manofstick** [comment]
@akbcode 

I've deployed as 1.1.3 on nuget. Let me know if it ain't workin'...
