### ISSUE TITLE
404 at http://fsprojects.github.io/FSharp.Quotations.Evaluator/

### ISSUE THREAD

**Issue by akeeton** [fsprojects/FSharp.Quotations.Evaluator#31]
### Description

> 404
> 
> File not found
> 
> The site configured at this address does not contain the requested file.

### Repro steps

1. Visit http://fsprojects.github.io/FSharp.Quotations.Evaluator/

### Expected behavior

Not a 404 (I don't know what to expect, this is my first time visiting the Quotations Evaluator).

### Actual behavior

404

### Known workarounds

N/A

### Related information 

N/A

**Comment by eiriktsarpalis** [comment]
Fixed by #33
