### ISSUE TITLE
Comprehensive benchmarking of quotation libraries

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/FSharp.Quotations.Evaluator#7]
Continuing from our previous discussion in [QuotationCompiler](https://github.com/eiriktsarpalis/QuotationCompiler/issues/1), I think it would be useful to have a comprehensive benchmarking suite for the quotation compilers. My experience on the different libraries is varied, so it would be nice to be able to precisely track differences as well gauging performance of the F# compiler itself. What do you think?

**Comment by manofstick** [comment]
No momentum on my side to get this started; and seems the same for QuotationCompiler, so I'm closing this.
