### ISSUE TITLE
Compile and CompileUntyped are maybe wrong

### ISSUE THREAD

**Issue by bleis-tift** [fsprojects/FSharp.Quotations.Evaluator#9]
Compile and CompileUntyped are the same Evaluate and EvaluateUntyped.

* https://github.com/fsprojects/FSharp.Quotations.Evaluator/blob/be7871ce0a/src/FSharp.Quotations.Evaluator/QuotationsEvaluator.fs#L736
* https://github.com/fsprojects/FSharp.Quotations.Evaluator/blob/be7871ce0a/src/FSharp.Quotations.Evaluator/QuotationsEvaluator.fs#L742

now:

```fsharp
QuotationEvaluator.Evaluate <@ 1 + 1 @> // 2
QuotationEvaluator.Compile <@ 1 + 1 @> // 2
```

expected:
```fsharp
QuotationEvaluator.Evaluate <@ 1 + 1 @> // 2
QuotationEvaluator.Compile <@ 1 + 1 @> // <fun:it@2>
```

I tried to create a pull request, but performance tests could not passed...

**Comment by manofstick** [comment]
Done
